# Generated by Django 6.0 on 2025-12-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(help_text='Загрузите фото высокого качества (1920x1080)', upload_to='site_settings/', verbose_name='Фон главной шапки')),
            ],
            options={
                'verbose_name': 'Настройки шапки',
                'verbose_name_plural': 'Настройки шапки',
            },
        ),
    ]
