# Generated by Django 6.0 on 2026-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text="Фото рядом с текстом 'История и Миссия'", null=True, upload_to='site_settings/', verbose_name="Фото в блоке 'О нас'"),
        ),
    ]
