# Generated by Django 6.0 on 2026-02-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sitesettings_options_sitesettings_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('embed_code', models.TextField(help_text='Вставьте сюда код Iframe или Script из Online Test Pad', verbose_name='Код вставки (Widget)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Онлайн тест',
                'verbose_name_plural': 'Онлайн тесты',
            },
        ),
    ]
